### ISSUE TITLE
[REQUEST]: update always on server mod

### ISSUE THREAD

**Issue by xczsonn** [norimicry/stardew-multiplayer-docker#26]
https://github.com/perkmi/Always-On-Server-for-Multiplayer

this mod is lastest

your bundle mod(https://www.nexusmods.com/stardewvalley/mods/20659/) have many bugs

**Comment by perkmi** [comment]
Hey, let me know if you run into any bugs with my version of always on server and ill get them fixed as fast as possible.

**Comment by cavazos-apps** [comment]
> Hey, let me know if you run into any bugs with my version of always on server and ill get them fixed as fast as possible.

Will do, appreciate it!

**Comment by xczsonn** [comment]
> Hey, let me know if you run into any bugs with my version of always on server and ill get them fixed as fast as possible.

hello! First of all, thank you for keeping the mod. Thanks to you, I've been having a great time these days. I don't have any bugs that make the game impossible yet, but I'll forward them to you if people report them. I like to play games with a lot of strangers. I have some issues. Among the options, there is a problem where 'lock player's chest' doesn't work. I don't know if it's a problem with the mod or this project, but you can open other people's boxes and steal items at will. And most people don't, but there has been trolling where some malicious people access other people's characters and put all the items in the shipping box. I'd love an option to set a password with a chat command when accessing a character. Thank you for your efforts. I hope my request isn't rude. I'm Korean, so I'm not familiar with English, so I hope there's no misunderstanding.

**Comment by cavazos-apps** [comment]
> Among the options, there is a problem where 'lock player's chest' doesn't work.

This could be the nature of how the container does _not_ go through the GoG/Steam authentication services and treats every character as a LAN player, which I do not see a way around since it requires a dummy host "player". If you wanted this functionality, you would have to run these mods on your own game without the docker portion, directly within your game installation and mods so that it could connect through Steam/GoG.

 > And most people don't, but there has been trolling where some malicious people access other people's characters and put all the items in the shipping box.

Sounds like you need to pick and choose who you let on the server more wisely.
