### ISSUE TITLE
[BUG]:  Server not Starting

### ISSUE THREAD

**Issue by bryanc12** [norimicry/stardew-multiplayer-docker#47]
Running Stardew Valley
chmod: changing permissions of 'start.sh': Operation not permitted
/usr/bin/xterm
cat: /data/Stardew/game/Mods/AutoLoadGame/config.json: Is a directory <- Kept repeating

Here's the output of the docker. I think we have to chmod it? And also what happened to the confi.json?
I'm deploying it with Portainer. The building and all process are all good, but the server not launching. And I'm able to view the VNC, but after the server loading the game it crash.

![image](https://github.com/user-attachments/assets/e983c4d5-a874-4028-8143-955963475968)
![image](https://github.com/user-attachments/assets/0f3da17e-1872-401a-b45c-15b25f4ab249)

**Comment by cavazos-apps** [comment]
```chmod: changing permissions of 'start.sh': Operation not permitted``` Looks like a permissions issue. This was not created with Portainer in mind as the supported deployment tool due to the separate platform Docker related files. It isn't just a simple docker-compose with an image from a repo. There are different docker-compose, Dockerfile, and docker-entrypoint files for each platform.
